### ISSUE TITLE
[BUGs] Relacionados a NF-e;

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#1319]
- [x] Data de emissão; Resolvido no #1300
- [x] Volumes transportados, não estão saindo no Danfe; Resolvido no #1300
- [x] Assinatura no XML de retorno; Resolvido no #1300
- [x] FCP não esta saindo nas tags do ICMSUFDEST. #1318 
- [x] Agrupamento dos pickings; #1322 
- [ ] Pagamento a prazo no Danfe / Duplicatas;

**- [ ] Cancelamento quando tem payment.order;** Conforme comentado abaixo.

Pessoal segue alguns Bugs que encontramos em um pre-golive de um novo cliente em produção. Estamos trabalhando para corrigir esses problemas ASAP.

cc: @gabrielcardoso21 @luismalta @ygcarvalh @bmessiaz @DiegoParadeda @sadamo

**Comment by mileo** [comment]
@mbcosta como foi feito o merge do https://github.com/odoo-brazil/l10n-brazil/pull/122 esse problema pode ser contornado adicionando manualmente os itens a ordem de pagamento. Não pretendo resolver esse problema agora, mas aviso pra vcs ficarem ligados.

**Comment by mbcosta** [comment]
@mileo qual o problema que acontece no Cancelamento quando tem payment.order ? Tem um Log com a mensagem de erro ? Existe o teste dessa situação no modulo https://github.com/odoo-brazil/l10n-brazil/blob/12.0-mig-l10n_br_account_payment_cobranca/l10n_br_account_payment_order/tests/test_payment_order_inbound.py#L223

Qual o BUG foi encontrado no Agrupamento de Pickings ? Tem um Log com a mensagem de erro ou uma descrição de quando o problema o ocorre ? Essa funcionalidade está sendo usada em três módulos aqui no projeto l10n_br_stock_account, l10n_br_sale_stock e l10n_br_purchase_stock e a implementação é feita no modulo stock_picking_invoicing que está em outro projeto, o erro acontece na localização ou no modulo principal ? Esses módulos possuem testes. 

Por favor ao abrir um "issue", principalmente um BUG, é fundamental colocar uma descrição de quando ocorre o problema, o  Log com a mensagem de erro e se necessário alguma imagem sobre; porque como outros desenvolvedores vão poder entender ou mesmo ajudar sem essas informações ?

**Comment by mileo** [comment]
> Qual o BUG foi encontrado no Agrupamento de Pickings ? Tem um Log com a mensagem de erro ou uma descrição de quando o problema o ocorre ? Essa funcionalidade está sendo usada em três módulos aqui no projeto l10n_br_stock_account, l10n_br_sale_stock e l10n_br_purchase_stock e a implementação é feita no modulo stock_picking_invoicing que está em outro projeto, o erro acontece na localização ou no modulo principal ? Esses módulos possuem testes.
> 
> Por favor ao abrir um "issue", principalmente um BUG, é fundamental colocar uma descrição de quando ocorre o problema, o Log com a mensagem de erro e se necessário alguma imagem sobre; porque como outros desenvolvedores vão poder entender ou mesmo ajudar sem essas informações ?

Olá @mbcosta o bug do cancelamento acontece da seguinte forma:

- Uma fatura com modo de pagamento que é adicionado automaticamente a uma ordem de pagamento é confirmada;
- Seu documento fiscal é transmitido;
- Seu documento fiscal é cancelado;
- O raise do unlink da rollback na transação e então os dados do cancelamento não são concomitados.

Isso foi corrigido em um dos commits no https://github.com/OCA/bank-payment/pull/781 onde removíamos as linhas em draft do account.payment automaticamente, mas pelo análise do @pedrobaeza no PR não vai ser aceita essa alteração lá. Vamos ter que tratar no nível da localização.

Fiquei de separar aquele PR em PRs menores, mas não tive tempo de olhar isso ainda.

O que eu sugiro é que nos clientes mantenha-se a adição manual dos itens a ordem de pagamento, somente quando o documento fiscal estiver 100% revisado e correto.

**Comment by mbcosta** [comment]
@mileo 
"O raise do unlink da rollback na transação e então os dados do cancelamento não são concomitados."
          
O raise de qual objeto ? Seria o do account.move.line ? Seria esse raise:

psycopg2.IntegrityError: update or delete on table "account_move_line" violates foreign key constraint "account_payment_line_move_line_id_fkey" on table "account_payment_line"

Porque se for esse caso o que foi feito "Isso foi corrigido em um dos commits no OCA/bank-payment/781 onde removíamos as linhas em draft do account.payment automaticamente," pelo que vi não resolvia o problema, e na verdade isso acontece quando existe uma Ordem de Pagamento já Confirmada onde já não se pode apagar as account.payment.line e o que causa o erro é a definição do campo move_line_id no objeto account.payment.line que tem um ondele=restrict https://github.com/OCA/bank-payment/blob/12.0/account_payment_order/models/account_payment_line.py#L30 eu já havia tentando resolver isso sobre escrevendo o método unlink do account.move para não apagar as AMLs no caso CNAB, mas é preciso apaga-las procurei resolver isso no último commit do PR do l10n_br_account_payment_order https://github.com/OCA/l10n-brazil/pull/768/commits/9760ff849ba770520a329b0f89d63dec789f91ec vejam se isso resolve o problema.
