### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/l10n-brazil#189]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] l10n_br_account_product
- [ ] l10n_br_account_payment
- [ ] l10n_br_data_account
- [ ] l10n_br_account
- [ ] l10n_br_data_base
- [ ] l10n_br_crm_zip
- [ ] l10n_br_stock
- [ ] l10n_br_zip
- [ ] l10n_br_sale
- [ ] l10n_br_account_product_service
- [ ] l10n_br_sale_stock
- [ ] l10n_br_hr_timesheet_invoice
- [ ] l10n_br_purchase
- [ ] l10n_br_account_service
- [ ] l10n_br_data_account_product
- [ ] l10n_br_account_voucher
- [ ] l10n_br_delivery
- [ ] l10n_br_crm
- [ ] l10n_br_data_account_service
- [ ] l10n_br_base
- [ ] l10n_br_sale_service
- [ ] l10n_br_sale_product
- [ ] l10n_br_product

**Comment by rvalyi** [comment]
ping @danimaribeiro here you go

**Comment by danimaribeiro** [comment]
:+1: Lets start.
I think I can migrate those which I already tested (except account) - https://github.com/Trust-Code/l10n-brazil/tree/9.0

**Comment by rvalyi** [comment]
@danimaribeiro yep rebase a pull requests atop of 9.0 HEAD please.
1 independent pull request per module please.

**Comment by danimaribeiro** [comment]
I'll do it again the commits, the link I sent was done against odoo-brazil, rebase would be a mess.

**Comment by rvalyi** [comment]
@danimaribeiro as you want. You can still leave separate commits for separate concerns as you prefer. BTW Renato is still working to provide the fiscal tests, it's really a question of hours/few days. It's just that he got busy like hell these days.
