### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/l10n-brazil#2153]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list
- [x] l10n_br_account - By @rvalyi - #2865
- [x] l10n_br_account_due_list - By @rvalyi - #2268
- [x] l10n_br_account_nfe - By @rvalyi - #3273
- [x] l10n_br_account_payment_brcobranca - By @antoniospneto - #3226
- [x] l10n_br_account_payment_order - By @antoniospneto - #3222
- [x] l10n_br_account_withholding - By @rvalyi - #3862
- [x] l10n_br_base - By @mileo - #2164
- [x] l10n_br_coa - By @renatonlima - #2311
- [x] l10n_br_coa_generic - By @rvalyi - #2335
- [x] l10n_br_coa_simple - By @renatonlima - #2334
- [x] l10n_br_contract - By @CristianoMafraJunior - #3857
- [x] l10n_br_crm - By @mileo - #2177
- [x] l10n_br_cte - By @rvalyi - #3663
- [x] l10n_br_cte_spec - By @rvalyi - #3586
- [x] l10n_br_currency_rate_update - By @renatonlima - #2359
- [x] l10n_br_delivery - By @rvalyi - #3571
- [x] l10n_br_delivery_nfe - By @antoniospneto - #3648
- [x] l10n_br_fiscal - By @rvalyi - #2805
- [x] l10n_br_fiscal_certificate - By @rvalyi - #2879
- [x] l10n_br_fiscal_dfe - By @rvalyi - #2881
- [ ] l10n_br_hr_contract - By @renatonlima - #3880
- [x] l10n_br_ie_search - By @rvalyi - #3223
- [x] l10n_br_mdfe - By @rvalyi - #3652
- [x] l10n_br_mdfe_spec - By @rvalyi - #3585
- [x] l10n_br_mis_report - By @antoniospneto - #3343
- [x] l10n_br_nfe - By @rvalyi - #3092
- [x] l10n_br_nfse - By @rvalyi - #2969
- [x] l10n_br_nfse_focus - By @rvalyi - #2971
- [ ] l10n_br_nfse_ginfes - By @DiegoParadeda - #2212
- [ ] l10n_br_nfse_paulistana - By @Tiago370 - #3803
- [x] l10n_br_portal - By @CristianoMafraJunior - #3864
- [x] l10n_br_product_contract - By @CristianoMafraJunior - #3870
- [x] l10n_br_purchase - By @rvalyi - #2912
- [x] l10n_br_purchase_request - By @kaynnan - #3719
- [x] l10n_br_purchase_stock - By @mbcosta - #3595
- [x] l10n_br_resource - By @rvalyi - #2444
- [x] l10n_br_sale - By @rvalyi - #2911
- [x] l10n_br_sale_commission - By @rvalyi - #3646
- [x] l10n_br_sale_invoice_plan - By @CristianoMafraJunior - #3873
- [x] l10n_br_sale_stock - By @rvalyi - #3570
- [x] l10n_br_setup_tests - By @rvalyi - #2809
- [x] l10n_br_stock_account - By @rvalyi - #3275
- [x] l10n_br_stock_account_report - By @mbcosta - #3640
- [ ] l10n_br_website_sale - By @CristianoMafraJunior - #3890
- [x] l10n_br_zip - By @mileo - #2178
- [ ] payment_cielo - By @renatonlima - #3730

Módulos que foram incluidos depois:

- [x] l10n_br_cnab_structure - By @antoniospneto - #3233
- [x] l10n_br_cnpj_search - By @Tiago370 - #3164
- [x] l10n_br_fiscal_closing - By @antoniospneto - #3231
- [x] l10n_br_hr - By @DiegoParadeda - #3031
- [x] l10n_br_nfe_spec - By @rvalyi - #2880
- [ ] l10n_br_nfse_barueri
- [ ] l10n_br_pos
- [ ] l10n_br_pos_cfe
- [ ] l10n_br_pos_nfce
- [ ] l10n_br_repair
- [ ] l10n_br_sale_blanket_order
- [x] l10n_br_stock - By @mileo - #2208
- [ ] l10n_br_website_sale
- [ ] l10n_br_website_sale_delivery
- [ ] payment_bacen_pix
- [ ] payment_pagseguro
- [x] spec_driven_model - By @rvalyi -  #2882

**Comment by alangalva** [comment]
Temos uma previsão para o app https://odoo-community.org/shop/hr-expense-advance-clearing-consolidation-11304?search=Advances#attr=21835

estar com a versão 16 ?

**Comment by mileo** [comment]
> Temos uma previsão para o app https://odoo-community.org/shop/hr-expense-advance-clearing-consolidation-11304?search=Advances#attr=21835
> 
> estar com a versão 16 ?

Este é um módulo de outro projeto da OCA, não esta sobre o guarda-chuva da localização brasileira. 

No link vc encontra o projeto principal: 

![image](https://github.com/OCA/l10n-brazil/assets/1975978/2a755776-c081-4ba6-8e88-1b54669108bf)

Para entender como a OCA é dividida sugiro a leitura das informações contidas no site oficial, como por exemplo:

https://odoo-community.org/get-involved/contribute
https://odoo-community.org/resources/projects-apps

Aqui vc encontra o roadmap da migração dos módulos do HR para a versão 16.0: https://github.com/OCA/hr/issues/1141 também é possível encontrar algum trabalho em progresso nos PRs em aberto do projeto https://github.com/OCA/hr/pulls

**Comment by alangalva** [comment]
Thanks

**Comment by rvalyi** [comment]
Não existe uma regra formal, mas na pratica, quando um modulo como este tem menos de uns 2k linhas de codigo, a "previsão" que vale é o Pull Request de migração. Ou seja, se existe e que fica verdinho nos testes e que nenhum PSC do projeto comentou que ta zoado, é o que vale. Se não tiver Pull Request, vc pode fazer o seu seguindo https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0
Ou então contratando alguém (de preferencia os autores ou contribuidores) para faze-lo.

Quando o modulo tem mais de uns 2k linhas, se trata de um modulo complexo e ai o que pode acontecer é que os autores podem não querer se curvar a sua agenda e vc vai ter que respeitar a agenda deles e esperar um pouco (pois podem querer fazer refatores numa versão anterior sem ninguém folgado aumentar o trabalho que eles tem para fazer forçando a barra para migrar antes do refator).  Na duvida perguntar no repo. Não é o caso desse modulo que é simples, mas é o caso dos principais módulos da localização aqui, então apenas explico o porque ainda não foram migrados para a v16 caso haja duvidas.

No caso o autor do modulo é a Escodoo daqui do Brasil com o @marcelsavegnago mas como o Luis falou o assunto pertence do repo OCA/hr.

**Comment by marcelsavegnago** [comment]
Sobre o módulo de consolidação de adiantamentos de despesa de viagem, por ora nossa previsão é que em breve vamos colocar esforços para migrar este módulo para versão 14.0. Porém, dependemos da demanda dos nossos projetos e até então esta migração ainda não é prioridade para nós.

Massss se alguém estiver disposto a migrar eu sugiro começar a migração para 14.0 antes de ir para 16.0 e ficarei feliz em revisar :)

**Comment by antoniospneto** [comment]
@rvalyi @marcelsavegnago 

se puder acrescentar ali na lista como pendentes:
- [ ] [l10n_br_account_nfe](https://github.com/OCA/l10n-brazil/tree/14.0/l10n_br_account_nfe)
- [ ] [l10n_br_account_withholding](https://github.com/OCA/l10n-brazil/tree/14.0/l10n_br_account_withholding)
- [ ] [l10n_br_cnab_structure](https://github.com/OCA/l10n-brazil/tree/14.0/l10n_br_cnab_structure)
- [ ] [l10n_br_cnpj_search](https://github.com/OCA/l10n-brazil/tree/14.0/l10n_br_cnpj_search)
- [ ] [l10n_br_contract](https://github.com/OCA/l10n-brazil/tree/14.0/l10n_br_contract)
- [ ] [l10n_br_cte_spec](https://github.com/OCA/l10n-brazil/tree/14.0/l10n_br_cte_spec)
- [ ] [l10n_br_delivery](https://github.com/OCA/l10n-brazil/tree/14.0/l10n_br_delivery)
- [ ] [l10n_br_delivery_nfe](https://github.com/OCA/l10n-brazil/tree/14.0/l10n_br_delivery_nfe)
- [ ] [l10n_br_fiscal_closing](https://github.com/OCA/l10n-brazil/tree/14.0/l10n_br_fiscal_closing)
- [ ] [10n_br_hr](https://github.com/OCA/l10n-brazil/tree/14.0/l10n_br_hr)
- [ ] [l10n_br_mdfe_spec](https://github.com/OCA/l10n-brazil/tree/14.0/l10n_br_mdfe_spec)
- [ ] [l10n_br_nfe_spec](https://github.com/OCA/l10n-brazil/tree/14.0/l10n_br_nfe_spec)
- [ ] [l10n_br_nfse_barueri](https://github.com/OCA/l10n-brazil/tree/14.0/l10n_br_nfse_barueri)
- [ ] [l10n_br_nfse_paulistana](https://github.com/OCA/l10n-brazil/tree/14.0/l10n_br_nfse_paulistana)
- [ ] [l10n_br_pos](https://github.com/OCA/l10n-brazil/tree/14.0/l10n_br_pos)
- [ ] [l10n_br_pos_cfe](https://github.com/OCA/l10n-brazil/tree/14.0/l10n_br_pos_cfe)
- [ ] [l10n_br_pos_nfce](https://github.com/OCA/l10n-brazil/tree/14.0/l10n_br_pos_nfce)
- [ ] [l10n_br_product_contract](https://github.com/OCA/l10n-brazil/tree/14.0/l10n_br_product_contract)
- [ ] [l10n_br_purchase_request](https://github.com/OCA/l10n-brazil/tree/14.0/l10n_br_purchase_request)
- [ ] [l10n_br_purchase_stock](https://github.com/OCA/l10n-brazil/tree/14.0/l10n_br_purchase_stock)
- [ ] [l10n_br_repair](https://github.com/OCA/l10n-brazil/tree/14.0/l10n_br_repair)
- [ ] [l10n_br_sale_blanket_order](https://github.com/OCA/l10n-brazil/tree/14.0/l10n_br_sale_blanket_order)
- [ ] [l10n_br_sale_commission](https://github.com/OCA/l10n-brazil/tree/14.0/l10n_br_sale_commission)
- [ ] [l10n_br_sale_invoice_plan](https://github.com/OCA/l10n-brazil/tree/14.0/l10n_br_sale_invoice_plan)
- [ ] [l10n_br_sale_stock](https://github.com/OCA/l10n-brazil/tree/14.0/l10n_br_sale_stock)
- [ ] [l10n_br_stock](https://github.com/OCA/l10n-brazil/tree/14.0/l10n_br_stock)
- [ ] [l10n_br_stock_account](https://github.com/OCA/l10n-brazil/tree/14.0/l10n_br_stock_account)
- [ ] [l10n_br_stock_account_report](https://github.com/OCA/l10n-brazil/tree/14.0/l10n_br_stock_account_report)
- [ ] [l10n_br_website_sale](https://github.com/OCA/l10n-brazil/tree/14.0/l10n_br_website_sale)
- [ ] [l10n_br_website_sale_delivery](https://github.com/OCA/l10n-brazil/tree/14.0/l10n_br_website_sale_delivery)
- [ ] [payment_bacen_pix](https://github.com/OCA/l10n-brazil/tree/14.0/payment_bacen_pix)
- [ ] [payment_pagseguro](https://github.com/OCA/l10n-brazil/tree/14.0/payment_pagseguro)
- [ ] [spec_driven_model](https://github.com/OCA/l10n-brazil/tree/14.0/spec_driven_model)

É que ai fica melhor para acompanhar a migração, valeu!

**Comment by rvalyi** [comment]
Important: read why the 16.0 branch needs to be reconstructed in #3490
