### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/l10n-brazil#416]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

Marque seu nome e o modulo que vc estiver migrando/revisando no documento:

https://docs.google.com/spreadsheets/d/1KnWbtAMyVoK-5uLsv3vv9Z8y7g5H6O-Tpu7E8bszxhY/edit#gid=0

# Modules to migrate
- [x] l10n_br_account
- [x] l10n_br_account_payment_order
- [x] l10n_br_account_product
- [x] l10n_br_account_product_service
- [x] l10n_br_account_service
- [x] l10n_br_base
- [x] l10n_br_crm
- [x] l10n_br_crm_zip
- [x] l10n_br_purchase
- [x] l10n_br_sale
- [x] l10n_br_sale_product
- [x] l10n_br_sale_service
- [x] l10n_br_sale_stock
- [x] l10n_br_stock
- [x] l10n_br_stock_account
- [x] l10n_br_zip
- [x] l10n_br_zip_correios

**Comment by rvalyi** [comment]
guys, as nothing has been merged in 9.0 yet. The plan is to re-create the 9.0 branch very soon (and rebase the PR's against it). Then we will also rebase that 10.0 branch. Basically as soon as we have these structuring PR's merged: 
-  https://github.com/OCA/l10n-brazil/pull/386
-  https://github.com/OCA/l10n-brazil/pull/363

Thus we will minimize the discrepancy between latest 8.0 devs and 9.0 and 10.0. The other PR's have few commits and can be cherry picked without problem later. So basically if you want to speed the 10.0 migration please help us to get these important PR's in 8.0 first to avoid double working on these important topics.

**Comment by pedrobaeza** [comment]
OK, just tell me and I re-run the 8.0 to 9.0 migration script, and when you're ready, the 9.0 > 10.0 one.

**Comment by rvalyi** [comment]
@pedrobaeza yep, hopefully it will be ok early next week we will let you know. We are merging and reviewing at a good pace these days, these are the final miles of the important 8.0 refactors while the 9.0 has been dropped by many of us (still a few 9.0 projects with the open PR's done).

**Comment by renatonlima** [comment]
Hello guys,

We finished migrating the v10.0 modules, some modules have not been migrated. Now we are working on version 12.0 migration and the goal of the l10n-brazil project is until the next one to keep location synchronized with Odoo CE version 14.0.
