### ISSUE TITLE
Finalização dos trabalhos Akretion>OCA antes de iniciarmos a migração   9.0 e 10.0

### ISSUE THREAD

**Issue by renatonlima** [OCA/l10n-brazil#438]
Vou descrever aqui algumas tarefas que estamos trabalhamos nesta semana e que podem ser integradas na OCA antes de iniciarmos a migração:
- [x] Divisão das visões de faturas e NFe #363;
- [x] Completar wizard de exportacão de NFe para assinar o XML; (vai ser feito durante a migração da 10)
- [x] Retirar o método de serializacão de TXT; (vai ser feito durante a migração da 10)
- [x] Incluir os dados do imposto de II;
- [x] Base de calculo de impostos operação de importação;
- [x] Incluir nos relatórios de Analise de Faturas os valores (Total Sem impostos, Total com Impostos, Total de ICMS, Total de ICMS ST, Total de PIS, Total de COFINS e TOTAL de II) #437;
- [x] Filtrar nos relatórios de faturas os status sefaz_cancel, sefaz_denid, sefaz_export e sefaz_exception. #436
- [x] Refatorar o campo CEST (Código de enquadramento da substituição tributária)

**Comment by mileo** [comment]
=D

**Comment by mileo** [comment]
@renatonlima quais são as mudanças referentes ao CEST, estou com umas coisas pra subir referente a isso tb.

**Comment by renatonlima** [comment]
Basicamente tem problemas no design:
1. Hoje a forma como esta ligada as CEST ao NCM esta errada;
2. Não existe um cadastro de CESTs
3. O Campo não esta sendo propagado na invoice de forma correta.

Eu já implementei o objeto CEST e a tabela de test, estou fazendo as outras mudanças no relacionamento dos objetos e a propagação da informação do CEST, quando eu subir o PR você pode dar uma olhada, sobre este tema o que você esta mudando? É importante a gente sincronizar isso para não trabalharmos na mesma coisa.

**Comment by danimaribeiro** [comment]
Não tem necessidade de se ter um cadastro de CEST, o mesmo pode ser apenas uma propriedade no produto com a seguinte lógica.
Se não existir no produto, usa o CEST da NCM (maioria dos casos), se existir mais de um CEST por NCM você cadastra ele no produto.

**Comment by mileo** [comment]
@renatonlima tem umas alterações na nossa branch, fiz um rebase da nossa branch com a OCA e sobraram algumas coisas da CEST que parecem não ter sido enviadas, acredito ser referente ao item 3.

Mas de toda forma como vc disse:
1) A forma que esta ligado com NCM esta errada, deve ser ligada ao produto, pois produtos diferentes com NCM iguais podem ter CEST diferentes;
2) Não tem um cadastro realmente, o @danimaribeiro havia compilado uma tabela de cest no PR #247 mas eu eu esqueci de subir. Favor considerar a mesma https://github.com/OCA/l10n-brazil/files/51145/CEST.xlsx e incluir ele como autor se possível.

Vc deve lembrar de colocar tb um domínio entre a NCM e a CEST no cadastro de produto.

**Comment by renatonlima** [comment]
@danimaribeiro,

Te explico a necessidade de se ter um cadastro o cadastro de CEST:
1. Atualmente o relacionamento da CEST com o NCM esta errado, porque um NCM por ter várias CESTs, por exemplo: o NCM 2201.10.00 tem as seguintes CESTs:

03.001.00 - Água em garrafa de vidro, retornável ou não, com capacidade de até 500 ml
03.002.00 - Água em embalagem com capacidade igual ou superior a 5.000 ml
03.003.00 - Água em embalagem de vidro, não retornável, com capacidade de até 300 ml
03.004.00 - Água em garrafa plástica de 1.500 ml
03.005.00 - Água em copos plásticos e embalagem plástica com capacidade de até 500 ml
1. Deve ter apenas o CEST a nível de produto, e no cadastro do produto ao selecionar um NCM, permitir lista as CESTs apenas do NCM do produto.
2. Se o campo CEST é apenas um campo texto, você pode facilmente escolher uma CEST que não pertence ao NCM e gerar um erro ao criar um NFe.

**Comment by danimaribeiro** [comment]
Se ele cadastrar errado também pode dar erro.

**Comment by rvalyi** [comment]
@danimaribeiro @mileo @renatonlima e meio off-topic, mas so para vcs se ligar tb nesse PR do @legalsylvain para aumentar a confiabilidade quando o usuario preenche o NCM de um produto: para restringir por categoria de produto e limitar os erros: https://github.com/OCA/account-fiscal-rule/pull/54

**Comment by renatonlima** [comment]
@danimaribeiro 

No objeto CEST quem tem permissão é apenas o contador (permissão Account Manager), então se um usuário de vendas for cadastrar um produto ao adicionar o NCM ele só vai poder preencher campo CEST com as CEST daquele NCM, ele não consegue criar uma nova CEST.

@mileo 

Eu dei uma  breve olhada no arquivo que você falou, o problema é que ele esta bem desatualizado, pelo que eu vi não há nenhum commit, se houver eu posso até fazer um cherry-pick do commit e depois fazer outro commit corrigindo o arquivo, mas eu diria que o melhor é continuar com o arquivo que utilizei.
