### ISSUE TITLE
Contabilidade segundo as normas Brasileiras

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#651]
Visando atender as funcionalidades relacionadas a Lei n. 11.638/07 e das demais regulamentações posteriores. Em uma sequência lógica e proposital de enumero os itens que devem ser atacados:

1. Lançamentos contábeis e suas dependências;
2. Saldo das contas;
3. Balancete;
4. Balanço Patrimonial;
5. Contas patrimoniais e de resultado;
6. Encerramento do exercício;
7. Demonstrações contábeis;
8. Emissão do SPED ECD;
9. Motor genérico para realizar lançamentos contábeis a partir de campos de outros modelos;

Lembrando que o SPED Contábil deve estar em mente em todos os passos para ser necessário refatorar muita coisa no último passo.

Comentarei nesse issue os itens acima em mais detalhes e PR relacionados

Brevemente enumero as ações algumas ações iniciais:

- [ ] Juntar o l10n_br_account com o l10n_br_account_product criando um módulo "l10n_br_fiscal" somente para função fiscal;
- [ ] Refazer o l10n_br_account segundo especificações deste Issue;
- [ ] Utilizando https://github.com/sped-br/python-sped/tree/master/sped/ecd como dependência para emissão do ECD;
- [ ] Permitir o uso da contabilidade gerencial ou da contabilidade completa pela lei 11.638/07;
- [ ] Criar um menu específico para contabilidade e renomear o menu "**Accounting**" do core para "**Faturamento**" movendo os **submenus** da sessão contabilidade para módulo Brasileiro;

**Comment by mileo** [comment]
1 - Lançamentos contábeis e suas dependências:
==============================

1.1 Plano de contas, plano de contas referencial e sua forte relação com os relatórios contábeis:
-------------------------------------------------------------------------------------------------------------------------------

Ao analisar o manual do ECD e alguns registros de SPED ECD de clientes:

Vemos os principais blocos:

I050 - Plano de contas da empresa;
I051 - Link entre a conta do plano de contas da empresa e o plano de contas referencial ( dentre os quais existem diversas opções dependendo da empresa);
I052 - Link entre a conta do plano de contas e os relatórios contábeis:

Por exemplo:
```
|I050|01012016|01|S|1|1||ATIVO|
|I050|01012016|01|S|2|1.1|1|ATIVO CIRCULANTE|
|I050|01012016|01|S|3|1.1.1|1.1|DISPONIBILIDADES|
|I050|01012016|01|S|4|1.1.1.1|1.1.1|CAIXA GERAL|
|I050|01012016|01|S|5|1.1.1.1.02|1.1.1.1|FUNDO FIXO|
|I050|01012016|01|A|6|1.1.1.1.02.0001|1.1.1.1.02|FUNDO FIXO|
|I051|1||1.01.01.01.01|
|I052||BP1.1.01.001|
```

- [ ] Melhorias no plano de contas;
- [ ] Link entre o plano da empresa e o plano referencial;
- [ ] Importação dos diversos planos de contas referenciais;
- [ ] Melhorias no motor de relatório mis_builder para criar uma forte relação entre a linha do relatório e o plano de contas;

1.2 Lançamentos contábeis
--------------------------------------

**Registro I200: Lançamento Contábil**

Este registro define o cabeçalho do lançamento contábil. São utilizados três tipos de lançamento:

1) Tipo E: lançamentos de encerramento das contas de resultado;
2) Tipo N: demais lançamentos, denominados lançamentos normais;
3) Tipo X: lançamentos extemporâneos, que abrangem, entre outros, os lançamentos previstos nos itens 31 a 36 da Interpretação Técnica Geral (ITG) 2000 (R1) - Escrituração Contábil, do Conselho Federal de Contabilidade, publicada em 12 de dezembro de 2014. 

**Registro I250: Partidas do Lançamento**

Este registro identifica todas as contrapartidas do valor do lançamento informado no registro I200 (cabeçalho do lançamento), ou seja, o somatório de todas as contrapartidas a crédito e o somatório de todas as contrapartidas a débito devem ser iguais ao valor do lançamento informado no registro I200.

Além disso, o somatório de todas as contrapartidas a crédito e o somatório de todas as contrapartidas a débito, para uma determinada conta contábil/centro de custos, devem ser iguais, respectivamente, ao valor dos débitos e  e ao valor dos créditos informados no registro de saldos mensais (I155) para essa conta contábil/centro de custos.

```
|I200|4113|010920XY|9999,99|N|
|I250|2.1.1.3.01.0042||8000,00|C|||APROPRIAÇÃO DA NOTA FISCAL 1234 ACME S/A EM 30.06.20XY.||
|I250|2.1.1.4.01.0010||1999,99|C|||APROPRIAÇÃO DE TRIBUTOS FEDERAIS RETIDOS SOB NOTA FISCAL 1234 ACME S/A.||
|I250|4.1.2.1.01.0006||9999,99|D|||APROPRIAÇÃO DA NOTA FISCAL 1234 ACME S/A, REFERENTE A [...] EM 30/06/20XY.||
```

**Comment by mileo** [comment]
2 - Saldo das contas
============

2.1 Saldo periódico mensal
--------------------------------------

**Registro I155: Detalhe dos Saldos Periódicos**

O registro I155, que é filho do registro I150, informa os saldos das contas contábeis, trazendo o total dos débitos e créditos mensais para as contas patrimoniais e de resultado. 

Os saldos devem ser informados por mês, ou seja, deve haver um registro I150 por mês. 

```
|I150|010120XY|310120XY|
|I155|1.1.1.1.02.0001||9999,99|D|999,99|999,99|999,99|D|
[...]
|I150|010220XY|290220XY|
|I155|1.1.1.1.02.0001||9999,99|D|999,99|9999,99|9999,99|D|
[...]
|I150|010320XY|310320XY|
|I155|1.1.1.1.02.0001||9999,99|D|999,99|9999,99|9999,99|D|
[...]
Outros meses
[...]
|I150|011120XY|301120XY|
|I155|1.1.1.1.02.0001|9999,99|D|999,99|9999,99|9999,99|D|
```
 * saldo das contas foi omitido de forma proposital.

2.2 Saldo contas de encerramento antes do resultado
--------------------------------------------------------------------------

**Registro I350: Saldo das Contas de Resultado Antes do Encerramento – Identificação da Data** 

Este registro identifica o período relativo aos saldos contábeis das contas de resultado antes do encerramento. A periodicidade do saldo é, no máximo, mensal, mas poderá conter fração de mês nos casos de abertura, fusão, cisão, incorporação ou extinção. 

É possível informar uma ou mais apurações de resultado no período. Para isso, basta informar as datas para cada uma das apurações de resultado neste registro e informar o saldo final de cada conta de resultado antes do encerramento no registro I355. 

```
|I350|311220XY|
|I355|3.1.1.1.01.0001||9999,99|C|
|I355|3.1.1.1.02.0002||9999,99|C|
|I355|3.1.1.1.02.0003||9999,99|C|
|I355|3.1.1.5.03.0001||9999,99|D|
|I355|3.1.1.5.03.0002||9999,99|D|
|I355|3.1.1.5.03.0004||9999,99|D|
[...]
```

**Comment by mileo** [comment]
Demonstrações contábeis
================

**Registro J005: Demonstrações Contábeis**

As demonstrações contábeis serão exibidas na mesma ordem em que as linhas forem inseridas no arquivo.

Pelo registro I052 – Indicação dos Códigos de Aglutinação – é feita uma correlação entre as linhas das demonstrações contábeis com as contas analíticas do Plano de Contas (registro I050).

O PGE do Sped Contábil totaliza os registros de saldos periódicos (registro I155), na data do balanço, com base no código de aglutinação (registro I052). O valor assim obtido é confrontado com as informações constantes do Balanço 

Patrimonial (registro J100). O mesmo procedimento é adotado para conferência dos valores lançados na Demonstração dos Resultados (registro J150) e para a Demonstração dos Lucros ou Prejuízos Acumulados (DLPA)/Demonstração das Mutações do Patrimônio Líquido (registros J210 e J215). Em relação à Demonstração do Resultado do Exercício (registro
J150), os valores totalizados são obtidos dos saldos das contas de resultado antes do encerramento (registro I355)

```
|J001|0|
|J005|010120XY|311220XY|1||
```

**Registro J100: Balanço Patrimonial**

Neste registro deve ser informado o Balanço Patrimonial da pessoa jurídica a partir dos códigos de aglutinação informados no registro I052. O nível de detalhamento das demonstrações contábeis é de responsabilidade exclusiva pessoa
jurídica. Os registros devem ser gerados na mesma ordem em que devem ser visualizados. 

```
|J100|BP1|1|1|ATIVO|9999,99|D||9999,99|D||
|J100|BP1.1|2|1|ATIVO CIRCULANTE|9999,99|D||9999,99|D||
|J100|BP1.1.01|3|1|Disponibilidades|9999,99|D||9999,99|D||
|J100|BP1.1.01.001|4|1|Caixa|9999,99|D||9999,99|D||
|J100|BP1.1.01.002|4|1|Bancos|9999,99|D||9999,99|C||
|J100|BP1.1.01.003|4|1|Aplicações Financeiras|9999,99|D||9999,99|D||
|J100|BP1.1.02|3|1|Créditos|9999,99|D||9999,99|D||
|J100|BP1.1.02.001|4|1|Clientes|9999,99|D||9999,99|D||
|J100|BP1.1.02.008|4|1|Adiantamentos de férias|9999,99|D||9999,99|D||
|J100|BP1.1.02.009|4|1|Adiantamento para Viagens|9999,99|D||9999,99|C||
|J100|BP1.1.03|3|1|Estoques|9999,99|D||9999,99|C||
|J100|BP1.1.03.002|4|1|Almoxarifado|9999,99|D||9999,99|C||
|J100|BP1.1.04|3|1|Tributos a Recuperar / Compensar|9999,99|D||9999,99|D||
|J100|BP1.1.04.004|4|1|IRRF a recuperar|9999,99|D||9999,99|D||
|J100|BP1.1.04.005|4|1|CSLL a recuperar|9999,99|D||9999,99|D||
|J100|BP1.1.04.008|4|1|IRPJ a recuperar|9999,99|D||9999,99|D||
|J100|BP1.1.05|3|1|Despesas Antecipadas|9999,99|D||9999,99|D||
|J100|BP1.1.05.001|4|1|Despesas Antecipadas|9999,99|D||9999,99|D||
|J100|BP1.2|2|1|ATIVO NÃO-CIRCULANTE|9999,99|D||9999,99|D||
|J100|BP1.2.02|3|1|Investimentos|9999,99|D||9999,99|C||
|J100|BP1.2.02.002|4|1|Investimentos|9999,99|D||9999,99|C||
|J100|BP1.2.03|3|1|Imobilizado|9999,99|D||9999,99|D||
[...]
|J100|BP2|1|2|PASSIVO|9999,99|C||9999,99|C||
|J100|BP2.1|2|2|PASSIVO CIRCULANTE|9999,99|C||9999,99|C||
|J100|BP2.1.02|3|2|Obrigações Trabalhistas e Sociais|9999,99|C||9999,99|C||
|J100|BP2.1.02.003|4|2|INSS a Recolher|9999,99|C||9999,99|C||
|J100|BP2.1.02.004|4|2|FGTS a Recolher|9999,99|C||9999,99|C||
|J100|BP2.1.02.010|4|2|Ressarcimento de Salários Cedidos|9999,99|C||9999,99|C||
|J100|BP2.1.02.011|4|2|Provisão de Férias|9999,99|C||9999,99|C||
|J100|BP2.1.02.013|4|2|Provisão de Férias - Diretores|9999,99|C||9999,99|C||
|J100|BP2.1.03|3|2|Obrigações Fiscais|9999,99|C||9999,99|C||
|J100|BP2.1.03.001|4|2|Impostos e Contribuições a Recolher|9999,99|C||9999,99|C||
[...]
|J100|BP2.1.04.001|4|2|Outras Obrigações|9999,99|C||9999,99|C||
[...]
|J100|BP2.1.08|3|2|Lucros, Dividendos e Participações a Pagar|9999,99|C||9999,99|C||
|J100|BP2.1.08.001|4|2|Dividendos a Pagar|9999,99|C||9999,99|C||
|J100|BP2.2|2|2|PASSIVO NÃO-CIRCULANTE|9999,99|C||9999,99|C||
|J100|BP2.2.05|3|2|Obrigações Fiscais|9999,99|C||9999,99|C||
|J100|BP2.2.05.001|4|2|IRPJ - Diferenças Temporárias - LP|9999,99|C||9999,99|C||
|J100|BP2.2.05.002|4|2|CSLL - Diferenças Temporárias LP|9999,99|C||9999,99|C||
|J100|BP2.4|2|2|PATRIMÔNIO LÍQUIDO|9999,99|C||9999,99|C||
|J100|BP2.4.01|3|2|Capital Social|9999,99|C||9999,99|C||
|J100|BP2.4.01.002|4|2|Capital Social|9999,99|C||9999,99|C||
|J100|BP2.4.04|3|2|Reservas de Lucros|9999,99|C||9999,99|C||
|J100|BP2.4.04.001|4|2|Reserva Legal|9999,99|C||9999,99|C||
|J100|BP2.4.04.005|4|2|Reserva de Retenção de Lucros|9999,99|C||9999,99|C||
```

**Registro J150: Demonstração do Resultado do Exercício (DRE)**

Neste registro deve ser informada a Demonstração do Resultado do Exercício (DRE) da pessoa jurídica a partir dos códigos de aglutinação informados no registro I052. O nível de detalhamento das demonstrações contábeis é de responsabilidade exclusiva da pessoa jurídica. Os registros devem ser gerados na mesma ordem em que devem ser
visualizados. 

```
|J150|DRE01|1|(+) RECEITA OPERACIONAL BRUTA|9999,99|P|||
|J150|DRE01.01|2|RECEITA OPERACIONAL|9999,99|P|||
|J150|DRE01.01.03|3|RECEITA|13549559,26|R|||
|J150|DRE05|1|(-) DEDUÇÕES DA RECEITA OPERACIONAL BRUTA|9999,99|N|||
|J150|DRE05.03|2|Impostos e Contribuições sobre Receita Operacional|9999,99|N|||
|J150|DRE05.03.02|3|COFINS|9999,99|D||||
|J150|DRE05.03.03|3|PIS|9999,99|D||||
|J150|DRE05.03.04|3|ISS|9999,99|D||||
|J150|DRE10|1|(=) RECEITA OPERACIONAL LÍQUIDA|9999,99|P|||
|J150|DRE15|1|(-) CUSTOS DOS PRODUTOS OU MERCADORIAS VENDIDAS E SERVIÇOS PRESTADOS|9999,99|N|||
|J150|DRE20|1|(=) LUCRO OPERACIONAL BRUTO|9999,99|P|||
|J150|DRE25|1|(-) DESPESA OPERACIONAL|9999,99|P|||
|J150|DRE25.02|2|Despesas Administrativas|9999,99|N|||
|J150|DRE25.02.01|3|Despesas Gerais|9999,99|D||||
|J150|DRE25.02.02|3|Despesas com Pessoal|9999,99|D||||
|J150|DRE25.02.03|3|Despesas Tributárias|9999,99|D||||
|J150|DRE25.02.07|3|Outras Despesas Operacionais|9999,99|D||||
|J150|DRE25.03|2|Despesas Financeiras|9999,99|N|||
|J150|DRE25.03.01|3|Despesas Financeiras|9999,99|D||||
|J150|DRE25.05|2|Receitas Financeiras|9999,99|P|||
|J150|DRE25.05.01|3|Receitas Financeiras|28232094,96|R|||
|J150|DRE25.06|2|Outras Receitas Operacionais|9999,99|P|||
|J150|DRE25.06.01|3|Outras Receitas Operacionais|598,20|R|||
|J150|DRE26|1|(+/-) RESULTADO FINANCEIRO LÍQUIDO|9999,99|N|||
|J150|DRE30|1|(=) LUCRO OPERACIONAL LÍQUIDO|9999,99|P|||
[...]
|J150|DRE40|1|(=) LUCRO ANTES DAS PROVISÕES PARA CSLL E IR|9999,99|P|||
|J150|DRE45|1|(-) PROVISÕES PARA CSLL E IR|9999,99|N|||
|J150|DRE45.01|2|Provisão para Contribuição Social sobre o Lucro Líquido|9999,99|N|||
|J150|DRE45.01.01|3|Provisão para Contribuição Social sobre o Lucro Líquido|9999,99|D||||
|J150|DRE45.02|2|Provisão para Imposto de Renda|9999,99|N|||
|J150|DRE45.02.01|3|Provisão para Imposto de Renda|9999,99|D||||
|J150|DRE50|1|(=) LUCRO ANTES DAS PARTICIPAÇÕES|9999,99|P|||
|J150|DRE55|1|(-) PARTICIPAÇÕES|9999,99|N|||
|J150|DRE60|1|(=) LUCRO LÍQUIDO DO PERÍODO|9999,99|P|||
```

**Registro J215: Fato Contábil que Altera a Conta Lucros Acumulados ou a Conta Prejuízos Acumulados ou Todo o Patrimônio Líquido**

Neste registro deverão ser informados os fatos contábeis que alteram a conta “Lucros Acumulados” ou a conta “Prejuízos Acumulados” ou quaisquer outras contas do Patrimônio Líquido. A ordem de apresentação dos registros J215 representará a ordem de exibição dos fatos contábeis da Demonstração das Mutações do Patrimônio Líquido (DMPL).

Portanto, o primeiro registro J215 deve conter o saldo inicial do código de aglutinação do registro J210. 

```
#TODO
```

**Comment by rvalyi** [comment]
@mileo isso ainda eh um work in progress, mas cheguei a fazer push do meu gerador de objetos do SPED a partir da especificacao. Isso ta na v11, mas com pouco esforco funciona na v10 e v12 tb:
https://github.com/akretion/l10n-brazil-sped
A ideia eh sobre-carregar para accrescentar as coisas que nao podem ser extraidas automaticamente dos PDFs de especificacao e para importar os registros a partir dos documentos XML ou dos registros Odoo, para deixar o trabalho manual minimo. A Akretion ira comunicar mais sobre essa P&D nas proximas semanas, portanto nao precisa divulgar muito isso por enquanto mas da para vcs olhar ja.
Isso usa um pouco a mesma estrategia do que o meu gerador de mixins Odoo a partir dos XSD's dos documentos fiscais e tb eh adherente com o que ja fazemos no https://github.com/OCA/intrastat-extrastat que seria o mais proximos do SPED brasileiro que ja existe no Odoo e na OCA.
